// <auto-generated />
using CarProject_OOP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarProject_OOP.Migrations
{
    [DbContext(typeof(CarManagementDbContext))]
    [Migration("20260925093425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarProject_OOP.Base.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarColor")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Cars");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Car");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CarProject_OOP.Concrete.ElectricCar", b =>
                {
                    b.HasBaseType("CarProject_OOP.Base.Car");

                    b.Property<float>("BatteryCapacity")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("ElectricCar");
                });

            modelBuilder.Entity("CarProject_OOP.Concrete.GasolineCar", b =>
                {
                    b.HasBaseType("CarProject_OOP.Base.Car");

                    b.Property<float>("FuelCapacity")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("GasolineCar");
                });

            modelBuilder.Entity("CarProject_OOP.Concrete.HybridCar", b =>
                {
                    b.HasBaseType("CarProject_OOP.Base.Car");

                    b.Property<float>("BatteryCapacity")
                        .HasColumnType("real");

                    b.Property<float>("FuelCapacity")
                        .HasColumnType("real");

                    b.ToTable("Cars", t =>
                        {
                            t.Property("BatteryCapacity")
                                .HasColumnName("HybridCar_BatteryCapacity");

                            t.Property("FuelCapacity")
                                .HasColumnName("HybridCar_FuelCapacity");
                        });

                    b.HasDiscriminator().HasValue("HybridCar");
                });
#pragma warning restore 612, 618
        }
    }
}
